message(STATUS "Example 1.7: variables for file system - CMAKE_CURRENT_SOURCE_DIR in cmake/example.cmake")
message(STATUS "CMAKE_CURRENT_SOURCE_DIR: ${CMAKE_CURRENT_SOURCE_DIR}")
message(STATUS "")
message(STATUS "Example 1.8: variables for file system - CMAKE_CURRENT_LIST_DIR in cmake/example.cmake")
message(STATUS "CMAKE_CURRENT_LIST_DIR: ${CMAKE_CURRENT_LIST_DIR}")
message(STATUS "")
