set(THIRDPARTY_NAME_LIST GTest OpenCV)

foreach(THIRDPARTY_NAME ${THIRDPARTY_NAME_LIST})
  message(STATUS "Start finding ${THIRDPARTY_NAME}.")

  find_package(${THIRDPARTY_NAME} QUIET HINTS ${${THIRDPARTY_NAME}_INSTALL_PATH}/lib/${${THIRDPARTY_NAME}_CMAKE_PATH})

  if(${THIRDPARTY_NAME}_FOUND)
    message(STATUS "Found ${THIRDPARTY_NAME}.")

    set(${THIRDPARTY_NAME}_INCLUDE_PATH ${${THIRDPARTY_NAME}_INSTALL_PATH}/include)

    message(STATUS "Set ${THIRDPARTY_NAME}_INCLUDE_PATH : ${${THIRDPARTY_NAME}_INCLUDE_PATH}.")
    include_directories(${${THIRDPARTY_NAME}_INCLUDE_PATH})
  endif()

  message(STATUS "Finish finding ${THIRDPARTY_NAME}.\n")
endforeach()
